### ISSUE TITLE
user_agent's length is too short

### ISSUE THREAD

**Issue by lyenliang** [Codefight-CMS/Codefight-CMS#1]
Hi, I just found that the maximum length of user_agent (which is 50) in cf_sessions table can be easily exceeded by a normal browser. 
For example, my browser is Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.101 Safari/537.36, which contains 114 characters.
Maybe setting user_agent's length from 50 to 200 would be better.

**Comment by dbashyal** [comment]
updated based on latest codeigniter doc.

commit: https://github.com/dbashyal/Codefight-CMS/commit/0112b738a1c82badb8da6ca24ff2a2f609ec081a

ref: https://ellislab.com/codeigniter/user-guide/libraries/sessions.html
